### ISSUE TITLE
Speed testing?

### ISSUE THREAD

**Issue by lucasjinreal** [Epiphqny/SOLO#1]
Did u compare the net forward speed compares to maskrcnn or other one-stage instance segmentation methods?

**Comment by YuqingWang1029** [comment]
> Did u compare the net forward speed compares to maskrcnn or other one-stage instance segmentation methods?

it is about 2.5fps without nms using the resnet-50 backbone on single TITAN-XP GPU for this implementation.

**Comment by lucasjinreal** [comment]
oh no.... MaskRCNN can runs at least 9.8 fps

**Comment by YuqingWang1029** [comment]
> oh no.... MaskRCNN can runs at least 9.8 fps

The author says it can run 22fps on resnet-50 with 512-size input, but has not released code yet.
