### ISSUE TITLE
About category target

### ISSUE THREAD

**Issue by ZhongYingMatrix** [Epiphqny/SOLO#2]
Hi~ thanks for ur work
I notice that in ur implement, all grids touching gt center regions are sampled as positive
https://github.com/Epiphqny/SOLO/blob/59a4c0389bc61e2519c7903151fd4d16dcee7ef1/mmdet/datasets/pipelines/transforms.py#L679
which is different from original paper 'grid (i, j) is considered as a positive sample if it falls into the center region of any ground truth mask'.
By my understanding, it's a positive sample as the grid center falls in center region.

**Comment by YuqingWang1029** [comment]
> Hi~ thanks for ur work
> I notice that in ur implement, all grids touching gt center regions are sampled as positive
> 
> https://github.com/Epiphqny/SOLO/blob/59a4c0389bc61e2519c7903151fd4d16dcee7ef1/mmdet/datasets/pipelines/transforms.py#L679
> 
> 
> which is different from original paper 'grid (i, j) is considered as a positive sample if it falls into the center region of any ground truth mask'.
> By my understanding, it's a positive sample as the grid center falls in center region.

Can’t fully understand your question, do you mean I should use less instead of equal in the center region boundary?
