### ISSUE TITLE
Bug in Mask-NMS

### ISSUE THREAD

**Issue by wjfwzzc** [Epiphqny/SOLO#3]
There seems to be a bug in the below line.
https://github.com/Epiphqny/SOLO/blob/59a4c0389bc61e2519c7903151fd4d16dcee7ef1/mmdet/models/anchor_heads/solo_head.py#L223
Might it be the following line?
```python3
iou = float(overlap.sum() + 1) / float(union.sum() + 1) 
```

And it might be faster to apply mask-nms on gpu.
![image](https://user-images.githubusercontent.com/5126316/71917014-19844b80-31ba-11ea-819a-29ff98ee87c4.png)

**Comment by YuqingWang1029** [comment]
> There seems to be a bug in the below line.
> 
> https://github.com/Epiphqny/SOLO/blob/59a4c0389bc61e2519c7903151fd4d16dcee7ef1/mmdet/models/anchor_heads/solo_head.py#L223
> 
> 
> Might it be the following line?
> ```python
> iou = float(overlap.sum() + 1) / float(union.sum() + 1) 
> ```
> 
> And it might be faster to apply mask-nms on gpu.
> ![image](https://user-images.githubusercontent.com/5126316/71917014-19844b80-31ba-11ea-819a-29ff98ee87c4.png)

Thank you very much for reporting this bug. I fixed the bug in https://github.com/Epiphqny/SOLO/commit/28a82d09a07742b324248ff8d4565e119fc30ca4
