### ISSUE TITLE
official implementation

### ISSUE THREAD

**Issue by taokong** [Epiphqny/SOLO#5]
check the official implementation here: [https://github.com/WXinlong/SOLO](https://github.com/WXinlong/SOLO)

**Comment by YuqingWang1029** [comment]
@taokong, thanks, i have implemented SOLOv2 based on the official implementation https://github.com/Epiphqny/SOLOv2

**Comment by taokong** [comment]
> @taokong, thanks, i have implemented SOLOv2 based on the official implementation https://github.com/Epiphqny/SOLOv2

Great and look forward to your results.

**Comment by YuqingWang1029** [comment]
Hi @taokong, The training is completed, and the mAP is 39.3 on COCO test-dev2017 dataset after 36 epochs(3x). In the original paper, the model achieves 39.7 after 72 epochs(6x).

**Comment by taokong** [comment]
> Hi @taokong, The training is completed, and the mAP is 39.3 on COCO test-dev2017 dataset after 36 epochs(3x). In the original paper, the model achieves 39.7 after 72 epochs(6x).

Thanks to report the performance, and it is impressive.
